source ~/.zsh/zsh.d/checks.zsh
source ~/.zsh/zsh.d/colors.zsh
source ~/.zsh/zsh.d/setopt.zsh
source ~/.zsh/zsh.d/exports.zsh
source ~/.zsh/zsh.d/prompt.zsh
source ~/.zsh/zsh.d/completion.zsh
source ~/.zsh/zsh.d/aliases.zsh
source ~/.zsh/zsh.d/bindkeys.zsh
source ~/.zsh/zsh.d/functions.zsh
source ~/.zsh/zsh.d/history.zsh
source ~/.zsh/zsh.d/zsh_hooks.zsh
source  ${DOTFILES}/z/z.sh
